import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import AuthContext from "@/context/session_context";
import { PayProvier } from "@/context/pay_context";
import { FarmSearchProvier } from "@/context/farm_search_context";
import SessionContext from "@/context/session_context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionContext>
        <PayProvier>
          <FarmSearchProvier>
            <body className={inter.className}>{children}</body>
          </FarmSearchProvier>
        </PayProvier>
      </SessionContext>
    </html>
  );
}
